services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_BASE_URL: ${API_BASE_URL:-https://be-tagihan-wifi.kentoes.my.id/api/v1}
    image: tagihan-wifi-fe:latest
    container_name: tagihan-wifi-fe
    ports:
      - "3005:3000"
    environment:
      - API_BASE_URL=${API_BASE_URL:-https://be-tagihan-wifi.kentoes.my.id/api/v1}
    env_file:
      - .env.local
    restart: unless-stopped
